Feature/id 315/offline download maps
CampusDelSaber/hermes pull request #64
Opened 2023-06-16 12:55 UTC by daniel-espinoza-79

2023-06-16 13:07 UTC, mmoralesv commented on app/src/main/java/com/isc/hermes/ActivitySelectRegion.java
> +            System.out.println("cheeee!!!!!!");
It needs to remove debug comments and add a Logging infrastructure.

2023-06-16 13:08 UTC, mmoralesv approved these changes

2023-06-16 16:00 UTC, GastonGutierrezC approved these changes

2023-06-19 22:30 UTC, aguirrekarina approved these changes

2023-06-20 04:34 UTC, zrock-dev requested changes
- Please be more careful with the naming of your classes and methods.
- Please pay more attention to the code formatting.

- Avoid the usage of deprecated methods/classes in order to have an up-to-date code.

- I have noticed that in your implementations you use Toast, I suggest you to move the lines that always repeat into a new class as a static method. 
   ex: ` Toast.makeText(getApplicationContext(), "THERE IS NO REGIONS DOWNLOADED YET", Toast.LENGTH_SHORT).show();`

- Could you please group the .xml files that are only being used by the offline mode implementation inside a directory?

2023-06-20 04:34 UTC, zrock-dev commented on app/src/main/java/com/isc/hermes/MainActivity.java
> +    public void OfflineModeSettings(View view) {
Watch out for this method.

2023-06-20 04:34 UTC, zrock-dev commented on app/src/main/java/com/isc/hermes/MainActivity.java
> +        startActivityForResult(intent, 177);
What represents the number 177? Please use it as a static attribute.

2023-06-20 04:34 UTC, zrock-dev commented on app/src/main/java/com/isc/hermes/OfflineModeSettingsActivityView.java
> +    public static Map<String, OfflineRegion> offlineRegionsNames;
why is it static?

2023-06-20 04:34 UTC, zrock-dev commented on app/src/main/java/com/isc/hermes/OfflineModeSettingsActivityView.java
> +    private Map<String, CardView> cardViews;
What's the difference between offlineRegionNames and cardViews?

2023-06-20 04:34 UTC, zrock-dev commented on app/src/main/java/com/isc/hermes/OfflineModeSettingsActivityView.java
> +    public static Map<String, OfflineRegion> offlineRegionsNames;
I think changing the name to “downloadedRegions” would make it more clear

2023-06-20 04:34 UTC, zrock-dev commented on app/src/main/java/com/isc/hermes/OfflineModeSettingsActivityView.java
> +        if (offlineRegion == null) return;
Maybe is better log or raise an error if the `offlineRegion` cannot be found or why is it null.

2023-06-20 04:34 UTC, zrock-dev commented on app/src/main/java/com/isc/hermes/OfflineModeSettingsActivityView.java
> +                    // ...
What is this comment for?

2023-06-20 04:34 UTC, zrock-dev commented on app/src/main/java/com/isc/hermes/model/RegionData.java
> +public class RegionData implements Parcelable {
Please, implement a repository to handle these objects.

2023-06-20 04:34 UTC, zrock-dev commented on app/src/main/java/com/isc/hermes/utils/offline/OfflineMapManager.java
> +    private OfflineManager offlineManager;
`OfflineMapManager` and `OfflineManager` are pretty much similar and is confusing

2023-06-20 04:34 UTC, zrock-dev commented on app/src/main/java/com/isc/hermes/utils/offline/OfflineMapManager.java
> +    private OfflineManager offlineManager;
This class contains several unused lines of code.

2023-06-20 04:34 UTC, zrock-dev commented on app/src/main/java/com/isc/hermes/utils/offline/OfflineMapManager.java
> +                , offlineRegionCallback);
Please pay attention to the formatting.

2023-06-20 04:34 UTC, zrock-dev commented on app/src/main/java/com/isc/hermes/utils/offline/OfflineMapManager.java
> +            regionName = String.format("", offlineRegion.getID());
You are declaring a parameter, but you're not using it inside that string.

2023-06-20 04:34 UTC, zrock-dev commented on app/src/main/java/com/isc/hermes/utils/offline/OfflineMapManager.java
> +    public String getRegionName(OfflineRegion offlineRegion) {
This method can easily be static, should it be here?

2023-06-20 04:34 UTC, zrock-dev commented on app/src/main/java/com/isc/hermes/utils/offline/OfflineMapManager.java
> +    public byte[] createMetadata(String regionName) {
This method could easily become static, should it be here?

2023-06-20 04:34 UTC, zrock-dev commented on app/src/main/res/values/strings.xml
> +    <string name="list_button_text">List</string>
Please, add a small commentary to tag this section as the offline mode components

2023-06-20 04:34 UTC, zrock-dev commented on app/src/main/res/layout/activity_main.xml
>          </androidx.cardview.widget.CardView>
Please, add a small commentary to tag this section as the offline mode components

2023-06-20 21:49 UTC, zrock-dev approved these changes
Good work, now all my observations have been solved.

2023-06-20 21:59 UTC, merged